project:
  type: website
  output-dir: docs

website:
  title: "Pocket Tiki Bar"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



